# Generated by Django 5.1.1 on 2024-09-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Film nomi')),
                ('description', models.TextField()),
                ('release_date', models.DateTimeField(verbose_name='Chiqgan sana')),
                ('made', models.CharField(max_length=50, verbose_name='Film qayerda chiqgan')),
                ('language', models.CharField(max_length=50, verbose_name='Film Tili')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Kommentator ismi')),
                ('description', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.movie')),
            ],
        ),
    ]
